export interface DemoUser {
  id: string;
  username: string | null;
  displayName: string | null;
  firstName: string | null;
  lastName: string | null;
  profileImageUrl: string | null;
  createdAt: string;
  weeklyPoints?: number;
  dayStreak?: number;
  bio?: string;
}

export const demoUsers: DemoUser[] = [
  {
    id: "friend-1",
    username: "alexc",
    displayName: "Alex Chen",
    firstName: "Alex",
    lastName: "Chen",
    profileImageUrl: null,
    createdAt: "2024-06-15",
    weeklyPoints: 485,
    dayStreak: 12,
    bio: "Fitness enthusiast and morning person",
  },
  {
    id: "friend-2",
    username: "jordant",
    displayName: "Jordan Taylor",
    firstName: "Jordan",
    lastName: "Taylor",
    profileImageUrl: null,
    createdAt: "2024-07-20",
    weeklyPoints: 320,
    dayStreak: 7,
    bio: "Building better habits one day at a time",
  },
  {
    id: "friend-3",
    username: "samr",
    displayName: "Sam Rivera",
    firstName: "Sam",
    lastName: "Rivera",
    profileImageUrl: null,
    createdAt: "2024-05-10",
    weeklyPoints: 560,
    dayStreak: 21,
    bio: "Marathon runner and productivity nerd",
  },
  {
    id: "friend-4",
    username: "morgank",
    displayName: "Morgan Kim",
    firstName: "Morgan",
    lastName: "Kim",
    profileImageUrl: null,
    createdAt: "2024-08-01",
    weeklyPoints: 280,
    dayStreak: 5,
    bio: "Just getting started on my journey",
  },
  {
    id: "user-4",
    username: "morgkim",
    displayName: "Morgan Kim",
    firstName: "Morgan",
    lastName: "Kim",
    profileImageUrl: null,
    createdAt: "2024-09-15",
    weeklyPoints: 190,
    dayStreak: 3,
    bio: "Working on consistency",
  },
  {
    id: "user-5",
    username: "caseyp",
    displayName: "Casey Park",
    firstName: "Casey",
    lastName: "Park",
    profileImageUrl: null,
    createdAt: "2024-08-20",
    weeklyPoints: 340,
    dayStreak: 8,
    bio: "Focus and determination",
  },
  {
    id: "req-1",
    username: "caseypark",
    displayName: "Casey Park",
    firstName: "Casey",
    lastName: "Park",
    profileImageUrl: null,
    createdAt: "2024-10-01",
    weeklyPoints: 275,
    dayStreak: 6,
    bio: "Looking for accountability partners",
  },
  {
    id: "req-2",
    username: "rileyj",
    displayName: "Riley Johnson",
    firstName: "Riley",
    lastName: "Johnson",
    profileImageUrl: null,
    createdAt: "2024-09-01",
    weeklyPoints: 410,
    dayStreak: 14,
    bio: "Health and wellness advocate",
  },
  {
    id: "u1",
    username: "sarahm",
    displayName: "Sarah M",
    firstName: "Sarah",
    lastName: "M",
    profileImageUrl: null,
    createdAt: "2024-06-01",
    weeklyPoints: 210,
    dayStreak: 15,
    bio: "Marathon training leader",
  },
  {
    id: "u2",
    username: "lisak",
    displayName: "Lisa K",
    firstName: "Lisa",
    lastName: "K",
    profileImageUrl: null,
    createdAt: "2024-07-01",
    weeklyPoints: 180,
    dayStreak: 10,
    bio: "Running and strength training",
  },
  {
    id: "u3",
    username: "emmat",
    displayName: "Emma T",
    firstName: "Emma",
    lastName: "T",
    profileImageUrl: null,
    createdAt: "2024-08-01",
    weeklyPoints: 165,
    dayStreak: 8,
    bio: "New to the running game",
  },
  {
    id: "u4",
    username: "dadwilliams",
    displayName: "Dad",
    firstName: "Dad",
    lastName: "",
    profileImageUrl: null,
    createdAt: "2024-10-15",
    weeklyPoints: 70,
    dayStreak: 4,
    bio: "Family first",
  },
  {
    id: "u5",
    username: "tommy",
    displayName: "Tommy",
    firstName: "Tommy",
    lastName: "",
    profileImageUrl: null,
    createdAt: "2024-10-16",
    weeklyPoints: 55,
    dayStreak: 3,
    bio: "Doing chores for points",
  },
  {
    id: "opp-1",
    username: "jakem",
    displayName: "Jake M",
    firstName: "Jake",
    lastName: "M",
    profileImageUrl: null,
    createdAt: "2024-05-01",
    weeklyPoints: 95,
    dayStreak: 11,
    bio: "Fitness Fanatics captain",
  },
  {
    id: "opp-2",
    username: "marias",
    displayName: "Maria S",
    firstName: "Maria",
    lastName: "S",
    profileImageUrl: null,
    createdAt: "2024-06-01",
    weeklyPoints: 85,
    dayStreak: 9,
    bio: "HIIT enthusiast",
  },
  {
    id: "available-2",
    username: "mikejones",
    displayName: "Mike Jones",
    firstName: "Mike",
    lastName: "Jones",
    profileImageUrl: null,
    createdAt: "2024-10-15",
    weeklyPoints: 380,
    dayStreak: 12,
    bio: "Tech professional staying active",
  },
  {
    id: "available-3",
    username: "emilyr",
    displayName: "Emily Roberts",
    firstName: "Emily",
    lastName: "Roberts",
    profileImageUrl: null,
    createdAt: "2024-09-20",
    weeklyPoints: 290,
    dayStreak: 7,
    bio: "Yoga instructor and mindfulness coach",
  },
  {
    id: "available-4",
    username: "davidl",
    displayName: "David Lee",
    firstName: "David",
    lastName: "Lee",
    profileImageUrl: null,
    createdAt: "2024-08-10",
    weeklyPoints: 445,
    dayStreak: 24,
    bio: "Early riser and habit hacker",
  },
  {
    id: "available-5",
    username: "sarahw",
    displayName: "Sarah Williams",
    firstName: "Sarah",
    lastName: "Williams",
    profileImageUrl: null,
    createdAt: "2024-07-05",
    weeklyPoints: 310,
    dayStreak: 9,
    bio: "Mom of 3 making time for wellness",
  },
  {
    id: "available-6",
    username: "jasonb",
    displayName: "Jason Brown",
    firstName: "Jason",
    lastName: "Brown",
    profileImageUrl: null,
    createdAt: "2024-11-10",
    weeklyPoints: 175,
    dayStreak: 4,
    bio: "Just started my habit journey",
  },
  {
    id: "available-7",
    username: "amandac",
    displayName: "Amanda Chen",
    firstName: "Amanda",
    lastName: "Chen",
    profileImageUrl: null,
    createdAt: "2024-06-20",
    weeklyPoints: 495,
    dayStreak: 30,
    bio: "30-day streak champion",
  },
  {
    id: "available-8",
    username: "chrisp",
    displayName: "Chris Patterson",
    firstName: "Chris",
    lastName: "Patterson",
    profileImageUrl: null,
    createdAt: "2024-10-01",
    weeklyPoints: 260,
    dayStreak: 6,
    bio: "Building consistency one day at a time",
  },
];

export function getDemoUser(userId: string): DemoUser | undefined {
  return demoUsers.find(u => u.id === userId);
}

export function getAvailableUsers(): DemoUser[] {
  return demoUsers.filter(u => u.id.startsWith("available-"));
}

export function getAllActiveUsers(): DemoUser[] {
  return demoUsers;
}
