import { useState, useEffect, useRef } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Brain,
  RefreshCw,
  TrendingUp,
  TrendingDown,
  Minus,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Lightbulb,
  ChevronDown,
  ChevronUp,
  Calendar,
  CalendarDays,
  CalendarRange,
  Sparkles
} from "lucide-react";

interface InsightResponse {
  headline: string;
  status: "aligned" | "drifting" | "needs_attention";
  mainInsight: string;
  strengths: string[];
  concerns: string[];
  suggestion: string;
  momentum: "up" | "steady" | "down";
  period: string;
  periodLabel: string;
  startDate: string;
  endDate: string;
  daysAnalyzed: number;
  totalPoints: number;
  avgDailyPoints: number;
  generatedAt: string;
}

type Period = "thisWeek" | "lastWeek" | "thisMonth" | "season";
type Tone = "direct" | "analytical" | "gentle" | "challenging";

interface InsightEngineCardProps {
  tone?: Tone;
  useMockData?: boolean;
}

const mockInsight: InsightResponse = {
  headline: "Strong momentum, minor gaps in morning routine",
  status: "aligned",
  mainInsight:
    "You've been consistent with your core habits this week, completing 85% of your must-do tasks. Your evening routine is particularly strong, but morning tasks are showing some inconsistency.",
  strengths: [
    "Evening routine completion at 92%",
    "Workout consistency improved from last week",
    "No penalty points accumulated"
  ],
  concerns: ["Morning meditation missed 3 days this week"],
  suggestion:
    "Try linking your morning meditation to your existing coffee routine - it's a habit you never miss.",
  momentum: "up",
  period: "thisWeek",
  periodLabel: "this week",
  startDate: "2024-01-15",
  endDate: "2024-01-21",
  daysAnalyzed: 5,
  totalPoints: 245,
  avgDailyPoints: 49,
  generatedAt: new Date().toISOString()
};

export default function InsightEngineCard({
  tone = "direct",
  useMockData = false
}: InsightEngineCardProps) {
  const [selectedPeriod, setSelectedPeriod] = useState<Period>("thisWeek");
  const [isExpanded, setIsExpanded] = useState(false);
  const [insight, setInsight] = useState<InsightResponse | null>(
    useMockData ? mockInsight : null
  );
  const hasAutoGenerated = useRef(false);

  // --- Reasoning enhancements (no UI changes) ---
  // Cache insights by period so the engine can reason comparatively (week vs last week, etc.)
  const insightCache = useRef<Record<Period, InsightResponse | null>>({
    thisWeek: useMockData ? mockInsight : null,
    lastWeek: null,
    thisMonth: null,
    season: null
  });

  // Track the latest request so out-of-order responses don't overwrite newer insights
  const latestRequestId = useRef(0);

  const getComparePeriod = (period: Period): Period | null => {
    switch (period) {
      case "thisWeek":
        return "lastWeek";
      case "lastWeek":
        return "thisWeek";
      case "thisMonth":
        return "lastWeek";
      case "season":
        return "thisMonth";
      default:
        return null;
    }
  };

  const buildCompareSnapshot = (period: Period) => {
    const comparePeriod = getComparePeriod(period);
    if (!comparePeriod) return null;

    const compareInsight = insightCache.current[comparePeriod];
    if (!compareInsight) return null;

    // Keep this minimal and stable: enough for the server to compare patterns without leaking UI details.
    return {
      period: comparePeriod,
      status: compareInsight.status,
      momentum: compareInsight.momentum,
      totalPoints: compareInsight.totalPoints,
      avgDailyPoints: compareInsight.avgDailyPoints,
      daysAnalyzed: compareInsight.daysAnalyzed,
      startDate: compareInsight.startDate,
      endDate: compareInsight.endDate,
      generatedAt: compareInsight.generatedAt
    };
  };

  const generateInsightMutation = useMutation({
    mutationFn: async ({
      period,
      tone,
      requestId,
      compare
    }: {
      period: Period;
      tone: Tone;
      requestId: number;
      compare: ReturnType<typeof buildCompareSnapshot>;
    }) => {
      const response = await apiRequest("POST", "/api/ai/insight-engine", {
        period,
        tone,
        // Signals to deepen reasoning on the backend (backend can ignore safely if not implemented yet)
        reasoningDepth: "deep",
        include: {
          categories: true,
          penalties: true,
          schedules: true,
          obligations: true,
          milestones: true,
          trajectory: period === "thisWeek"
        },
        // Enables comparative reasoning (e.g., "improved vs last week", "drift started mid-week")
        compare,
        // Helps the backend avoid stale or duplicate processing (and helps you debug)
        requestId,
        // Optional: provides stable time reference (useful for "this week trajectory" calculations)
        clientContext: {
          nowIso: new Date().toISOString(),
          timezone: "America/New_York"
        }
      });
      return response.json();
    },
    onSuccess: (data: InsightResponse, variables) => {
      // Ignore stale / out-of-order responses
      if (variables.requestId !== latestRequestId.current) return;
      // Guard against server returning a different period than requested
      if (data?.period && data.period !== variables.period) return;

      insightCache.current[variables.period] = data;
      setInsight(data);
    }
  });

  // Auto-generate insight on mount (and ensure we use the latest selectedPeriod/tone)
  useEffect(() => {
    if (!useMockData && !hasAutoGenerated.current && !insight) {
      hasAutoGenerated.current = true;

      const requestId = ++latestRequestId.current;
      const compare = buildCompareSnapshot(selectedPeriod);
      generateInsightMutation.mutate({ period: selectedPeriod, tone, requestId, compare });
    }
  }, [useMockData, insight, selectedPeriod, tone]);

  const handleGenerate = () => {
    if (useMockData) {
      const updated = { ...mockInsight, period: selectedPeriod, generatedAt: new Date().toISOString() };
      insightCache.current[selectedPeriod] = updated;
      setInsight(updated);
      return;
    }

    const requestId = ++latestRequestId.current;
    const compare = buildCompareSnapshot(selectedPeriod);
    generateInsightMutation.mutate({ period: selectedPeriod, tone, requestId, compare });
  };

  const handlePeriodChange = (period: Period) => {
    setSelectedPeriod(period);

    // Immediately show cached insight for that period if available (feels smarter + enables comparison)
    const cached = insightCache.current[period];
    if (cached) {
      setInsight(cached);
    }

    if (useMockData) {
      const updated = { ...mockInsight, period, generatedAt: new Date().toISOString() };
      insightCache.current[period] = updated;
      setInsight(updated);
    } else {
      const requestId = ++latestRequestId.current;
      const compare = buildCompareSnapshot(period);
      generateInsightMutation.mutate({ period, tone, requestId, compare });
    }
  };

  const periodConfig: { value: Period; label: string; shortLabel: string; icon: typeof Calendar }[] =
    [
      { value: "thisWeek", label: "This Week", shortLabel: "Week", icon: Calendar },
      { value: "lastWeek", label: "Last Week", shortLabel: "Last", icon: CalendarDays },
      { value: "thisMonth", label: "This Month", shortLabel: "Month", icon: CalendarRange },
      { value: "season", label: "Season", shortLabel: "Season", icon: Sparkles }
    ];

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "aligned":
        return <CheckCircle2 className="h-4 w-4 text-green-500" />;
      case "drifting":
        return <AlertTriangle className="h-4 w-4 text-yellow-500" />;
      case "needs_attention":
        return <AlertCircle className="h-4 w-4 text-red-500" />;
      default:
        return null;
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "aligned":
        return (
          <Badge
            variant="outline"
            className="bg-green-500/10 text-green-600 border-green-500/30"
          >
            Aligned
          </Badge>
        );
      case "drifting":
        return (
          <Badge
            variant="outline"
            className="bg-yellow-500/10 text-yellow-600 border-yellow-500/30"
          >
            Drifting
          </Badge>
        );
      case "needs_attention":
        return (
          <Badge
            variant="outline"
            className="bg-red-500/10 text-red-600 border-red-500/30"
          >
            Needs Attention
          </Badge>
        );
      default:
        return null;
    }
  };

  const getMomentumIcon = (momentum: string) => {
    switch (momentum) {
      case "up":
        return <TrendingUp className="h-4 w-4 text-green-500" />;
      case "down":
        return <TrendingDown className="h-4 w-4 text-red-500" />;
      default:
        return <Minus className="h-4 w-4 text-muted-foreground" />;
    }
  };

  const periodLabels: Record<Period, string> = {
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    season: "Season"
  };

  const isLoading = generateInsightMutation.isPending;
  const hasError = generateInsightMutation.isError;
  const errorMessage = generateInsightMutation.error?.message || "Failed to generate insight";

  return (
    <Card data-testid="card-insight-engine">
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <Brain className="h-5 w-5 text-primary" />
            <CardTitle className="text-base font-semibold">Insight Engine</CardTitle>
          </div>
          <Button
            variant="ghost"
            size="icon"
            onClick={handleGenerate}
            disabled={isLoading}
            data-testid="button-refresh-insight-header"
          >
            <RefreshCw className={`h-4 w-4 ${isLoading ? "animate-spin" : ""}`} />
          </Button>
        </div>
        <div className="flex gap-1 mt-2">
          {periodConfig.map((p) => {
            const Icon = p.icon;
            const isSelected = selectedPeriod === p.value;
            return (
              <button
                key={p.value}
                onClick={() => handlePeriodChange(p.value)}
                disabled={isLoading}
                className={`flex-1 flex flex-col items-center gap-1 py-2 px-1 rounded-md transition-colors ${
                  isSelected
                    ? "bg-primary/10 text-primary border border-primary/30"
                    : "text-muted-foreground hover-elevate border border-transparent"
                } ${isLoading ? "opacity-50 cursor-not-allowed" : "cursor-pointer"}`}
                data-testid={`button-period-${p.value}`}
              >
                <Icon className="h-4 w-4" />
                <span className="text-xs font-medium">{p.shortLabel}</span>
              </button>
            );
          })}
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {hasError ? (
          <div className="flex flex-col items-center justify-center py-4 space-y-2 text-center">
            <AlertCircle className="h-8 w-8 text-destructive" />
            <p className="text-sm text-destructive font-medium">Something went wrong</p>
            <p className="text-xs text-muted-foreground">{errorMessage}</p>
            <Button
              variant="outline"
              size="sm"
              onClick={handleGenerate}
              data-testid="button-retry-insight"
            >
              <RefreshCw className="h-4 w-4 mr-2" />
              Try Again
            </Button>
          </div>
        ) : isLoading || !insight ? (
          <div className="flex flex-col items-center justify-center py-8 space-y-3">
            <div className="relative">
              <Brain className="h-12 w-12 text-primary/20" />
              <RefreshCw className="h-5 w-5 text-primary absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-spin" />
            </div>
            <p className="text-sm text-muted-foreground text-center">
              Analyzing your patterns...
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="flex items-start justify-between gap-2">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  {getStatusIcon(insight!.status)}
                  <h3 className="font-medium text-sm leading-tight">
                    {insight!.headline}
                  </h3>
                </div>
                <div className="flex items-center gap-2 flex-wrap">
                  {getStatusBadge(insight!.status)}
                  <div className="flex items-center gap-1 text-xs text-muted-foreground">
                    {getMomentumIcon(insight!.momentum)}
                    <span>
                      {insight!.momentum === "up"
                        ? "Trending up"
                        : insight!.momentum === "down"
                        ? "Trending down"
                        : "Steady"}
                    </span>
                  </div>
                </div>
              </div>
              <Button
                variant="ghost"
                size="icon"
                onClick={handleGenerate}
                disabled={isLoading}
                data-testid="button-refresh-insight"
              >
                <RefreshCw className={`h-4 w-4 ${isLoading ? "animate-spin" : ""}`} />
              </Button>
            </div>

            <p className="text-sm text-muted-foreground">{insight!.mainInsight}</p>

            <Button
              variant="ghost"
              size="sm"
              className="w-full justify-between"
              onClick={() => setIsExpanded(!isExpanded)}
              data-testid="button-expand-insight"
            >
              <span className="text-xs">{isExpanded ? "Show less" : "Show details"}</span>
              {isExpanded ? (
                <ChevronUp className="h-4 w-4" />
              ) : (
                <ChevronDown className="h-4 w-4" />
              )}
            </Button>

            {isExpanded && (
              <div className="space-y-4 pt-2 border-t">
                {insight.strengths.length > 0 && (
                  <div>
                    <h4 className="text-xs font-medium text-muted-foreground mb-2 flex items-center gap-1">
                      <CheckCircle2 className="h-3 w-3 text-green-500" />
                      Strengths
                    </h4>
                    <ul className="space-y-1">
                      {insight.strengths.map((strength, i) => (
                        <li key={i} className="text-sm text-muted-foreground pl-4">
                          {strength}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {insight.concerns.length > 0 && (
                  <div>
                    <h4 className="text-xs font-medium text-muted-foreground mb-2 flex items-center gap-1">
                      <AlertTriangle className="h-3 w-3 text-yellow-500" />
                      Areas to Watch
                    </h4>
                    <ul className="space-y-1">
                      {insight.concerns.map((concern, i) => (
                        <li key={i} className="text-sm text-muted-foreground pl-4">
                          {concern}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="bg-primary/5 rounded-md p-3">
                  <h4 className="text-xs font-medium mb-1 flex items-center gap-1">
                    <Lightbulb className="h-3 w-3 text-primary" />
                    Suggestion
                  </h4>
                  <p className="text-sm">{insight.suggestion}</p>
                </div>

                <div className="grid grid-cols-3 gap-2 text-center pt-2 border-t">
                  <div>
                    <div className="text-lg font-semibold">{insight.daysAnalyzed}</div>
                    <div className="text-xs text-muted-foreground">Days</div>
                  </div>
                  <div>
                    <div className="text-lg font-semibold">{insight.totalPoints}</div>
                    <div className="text-xs text-muted-foreground">Points</div>
                  </div>
                  <div>
                    <div className="text-lg font-semibold">{insight.avgDailyPoints}</div>
                    <div className="text-xs text-muted-foreground">Avg/Day</div>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
