import { useState, useEffect, useRef } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Brain,
  RefreshCw,
  TrendingUp,
  TrendingDown,
  Minus,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Lightbulb,
  ChevronDown,
  ChevronUp,
  Calendar,
  CalendarDays,
  CalendarRange,
  Sparkles
} from "lucide-react";

interface InsightResponse {
  headline: string;
  status: "aligned" | "drifting" | "needs_attention";
  mainInsight: string;
  strengths: string[];
  concerns: string[];
  suggestion: string;
  momentum: "up" | "steady" | "down";
  period: string;
  periodLabel: string;
  startDate: string;
  endDate: string;
  daysAnalyzed: number;
  totalPoints: number;
  avgDailyPoints: number;
  generatedAt: string;
}

type Period = "thisWeek" | "lastWeek" | "thisMonth" | "season";
type Tone = "direct" | "analytical" | "gentle" | "challenging";

interface InsightEngineCardProps {
  tone?: Tone;
  useMockData?: boolean;
}

const mockInsight: InsightResponse = {
  headline: "Strong momentum, minor gaps in morning routine",
  status: "aligned",
  mainInsight:
    "You've been consistent with your core habits this week, completing 85% of your must-do tasks. Your evening routine is particularly strong, but morning tasks are showing some inconsistency.",
  strengths: [
    "Evening routine completion at 92%",
    "Workout consistency improved from last week",
    "No penalty points accumulated"
  ],
  concerns: ["Morning meditation missed 3 days this week"],
  suggestion:
    "Try linking your morning meditation to your existing coffee routine - it's a habit you never miss.",
  momentum: "up",
  period: "thisWeek",
  periodLabel: "this week",
  startDate: "2024-01-15",
  endDate: "2024-01-21",
  daysAnalyzed: 5,
  totalPoints: 245,
  avgDailyPoints: 49,
  generatedAt: new Date().toISOString()
};

export default function InsightEngineCard({
  tone = "direct",
  useMockData = false
}: InsightEngineCardProps) {
  const [selectedPeriod, setSelectedPeriod] = useState<Period>("thisWeek");
  const [isExpanded, setIsExpanded] = useState(false);
  const [insight, setInsight] = useState<InsightResponse | null>(
    useMockData ? mockInsight : null
  );
  const hasAutoGenerated = useRef(false);

  // --- Reasoning enhancements (no UI changes) ---
  // Cache insights by period so toggling is instant and does NOT re-analyze every time.
  // Re-analysis happens only on full page refresh (new session) or explicit user refresh button.
  const insightCache = useRef<Record<Period, InsightResponse | null>>({
    thisWeek: useMockData ? mockInsight : null,
    lastWeek: null,
    thisMonth: null,
    season: null
  });

  // Track the latest request so out-of-order responses don't overwrite newer insights
  const latestRequestId = useRef(0);

  const getComparePeriod = (period: Period): Period | null => {
    switch (period) {
      case "thisWeek":
        return "lastWeek";
      case "lastWeek":
        return "thisWeek";
      case "thisMonth":
        return "lastWeek";
      case "season":
        return "thisMonth";
      default:
        return null;
    }
  };

  const buildCompareSnapshot = (period: Period) => {
    const comparePeriod = getComparePeriod(period);
    if (!comparePeriod) return null;

    const compareInsight = insightCache.current[comparePeriod];
    if (!compareInsight) return null;

    // Minimal, stable snapshot for comparative reasoning
    return {
      period: comparePeriod,
      status: compareInsight.status,
      momentum: compareInsight.momentum,
      totalPoints: compareInsight.totalPoints,
      avgDailyPoints: compareInsight.avgDailyPoints,
      daysAnalyzed: compareInsight.daysAnalyzed,
      startDate: compareInsight.startDate,
      endDate: compareInsight.endDate,
      generatedAt: compareInsight.generatedAt
    };
  };

  const generateInsightMutation = useMutation({
    mutationFn: async ({
      period,
      tone,
      requestId,
      compare,
      // Whether the backend should do a full expensive analysis, or a cheap render of the last snapshot.
      // We keep it "full" for now, but this flag future-proofs server behavior.
      analyzeMode
    }: {
      period: Period;
      tone: Tone;
      requestId: number;
      compare: ReturnType<typeof buildCompareSnapshot>;
      analyzeMode: "full" | "none";
    }) => {
      const response = await apiRequest("POST", "/api/ai/insight-engine", {
        period,
        tone,

        // --- Deep reasoning contract ---
        // The goal is task-grounded insights:
        // - name specific tasks that were missed or done
        // - tie categories to concrete task examples
        // - use points as a supporting signal, not the primary explanation
        reasoningDepth: "deep",
        reasoningPolicy: {
          // Disallow vague claims like "most tasks you attempt"
          banVagueProductivityLanguage: true,
          // Require grounding: each strength/concern must reference at least one concrete task or task-group
          requireTaskGrounding: true,
          // If insufficient task data, the model should say so rather than generalize
          preferInsufficientDataOverGuessing: true,
          // Points can be used, but only as supporting evidence (quantify), not as the primary reason (explain)
          pointsAreSupportingSignalOnly: true
        },

        // Tell the backend what to use for reasoning
        include: {
          // Make task language a first-class input (names + completion status + must/should/could)
          tasks: {
            names: true,
            completion: true,
            importance: true, // must/should/could
            categories: true,
            schedules: true,
            timestamps: true,
            // If your data model supports it, the server can use due dates for obligations
            dueDates: true
          },
          categories: true,
          penalties: true,
          schedules: true,
          obligations: true,
          milestones: true,
          // "thisWeek" should also include a trajectory read (early warning / direction)
          trajectory: period === "thisWeek",
          // Preference learning: let the engine lean into what the user reliably shows up for
          preferences: {
            likes: true,
            avoidances: true,
            consistencyLevers: true
          }
        },

        // Comparative reasoning: helps say "improved vs last week" with evidence
        compare,

        // Helps the backend avoid stale or duplicate processing (and helps you debug)
        requestId,

        // Optional: provides stable time reference (useful for "this week trajectory" calculations)
        clientContext: {
          nowIso: new Date().toISOString(),
          timezone: "America/New_York"
        },

        // Server may ignore this now; it’s a forward-compatible knob
        analyzeMode
      });
      return response.json();
    },
    onSuccess: (data: InsightResponse, variables) => {
      // Ignore stale / out-of-order responses
      if (variables.requestId !== latestRequestId.current) return;
      // Guard against server returning a different period than requested
      if (data?.period && data.period !== variables.period) return;

      insightCache.current[variables.period] = data;
      setInsight(data);
    }
  });

  // Auto-generate insight on mount (one-time per page load/session)
  useEffect(() => {
    if (!useMockData && !hasAutoGenerated.current && !insight) {
      hasAutoGenerated.current = true;

      const requestId = ++latestRequestId.current;
      const compare = buildCompareSnapshot(selectedPeriod);
      generateInsightMutation.mutate({
        period: selectedPeriod,
        tone,
        requestId,
        compare,
        analyzeMode: "full"
      });
    }
  }, [useMockData, insight, selectedPeriod, tone]);

  const handleGenerate = () => {
    // Explicit refresh: always re-analyze the currently selected period.
    if (useMockData) {
      const updated = {
        ...mockInsight,
        period: selectedPeriod,
        generatedAt: new Date().toISOString()
      };
      insightCache.current[selectedPeriod] = updated;
      setInsight(updated);
      return;
    }

    const requestId = ++latestRequestId.current;
    const compare = buildCompareSnapshot(selectedPeriod);
    generateInsightMutation.mutate({
      period: selectedPeriod,
      tone,
      requestId,
      compare,
      analyzeMode: "full"
    });
  };

  const handlePeriodChange = (period: Period) => {
    setSelectedPeriod(period);

    // Desired behavior:
    // - do NOT re-analyze on toggle if we already have an analyzed insight for that period in this session
    // - toggling should be instant and stable
    const cached = insightCache.current[period];
    if (cached) {
      setInsight(cached);
      return;
    }

    // If there's no cached result yet for this period in this session, analyze once.
    if (useMockData) {
      const updated = { ...mockInsight, period, generatedAt: new Date().toISOString() };
      insightCache.current[period] = updated;
      setInsight(updated);
      return;
    }

    const requestId = ++latestRequestId.current;
    const compare = buildCompareSnapshot(period);
    generateInsightMutation.mutate({
      period,
      tone,
      requestId,
      compare,
      analyzeMode: "full"
    });
  };

  const periodConfig: { value: Period; label: string; shortLabel: string; icon: typeof Calendar }[] =
    [
      { value: "thisWeek", label: "This Week", shortLabel: "Week", icon: Calendar },
      { value: "lastWeek", label: "Last Week", shortLabel: "Last", icon: CalendarDays },
      { value: "thisMonth", label: "This Month", shortLabel: "Month", icon: CalendarRange },
      { value: "season", label: "Season", shortLabel: "Season", icon: Sparkles }
    ];

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "aligned":
        return <CheckCircle2 className="h-4 w-4 text-green-500" />;
      case "drifting":
        return <AlertTriangle className="h-4 w-4 text-yellow-500" />;
      case "needs_attention":
        return <AlertCircle className="h-4 w-4 text-red-500" />;
      default:
        return null;
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "aligned":
        return (
          <Badge
            variant="outline"
            className="bg-green-500/10 text-green-600 border-green-500/30"
          >
            Aligned
          </Badge>
        );
      case "drifting":
        return (
          <Badge
            variant="outline"
            className="bg-yellow-500/10 text-yellow-600 border-yellow-500/30"
          >
            Drifting
          </Badge>
        );
      case "needs_attention":
        return (
          <Badge
            variant="outline"
            className="bg-red-500/10 text-red-600 border-red-500/30"
          >
            Needs Attention
          </Badge>
        );
      default:
        return null;
    }
  };

  const getMomentumIcon = (momentum: string) => {
    switch (momentum) {
      case "up":
        return <TrendingUp className="h-4 w-4 text-green-500" />;
      case "down":
        return <TrendingDown className="h-4 w-4 text-red-500" />;
      default:
        return <Minus className="h-4 w-4 text-muted-foreground" />;
    }
  };

  const periodLabels: Record<Period, string> = {
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    season: "Season"
  };

  const isLoading = generateInsightMutation.isPending;
  const hasError = generateInsightMutation.isError;
  const errorMessage = generateInsightMutation.error?.message || "Failed to generate insight";

  return (
    <Card data-testid="card-insight-engine">
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <Brain className="h-4 w-4 text-primary" />
            <CardTitle className="text-sm font-semibold">Insight Engine</CardTitle>
          </div>
          <div className="flex items-center gap-1">
            <div className="flex gap-0.5">
              {periodConfig.map((p) => {
                const isSelected = selectedPeriod === p.value;
                return (
                  <button
                    key={p.value}
                    onClick={() => handlePeriodChange(p.value)}
                    disabled={isLoading}
                    className={`px-2 py-1 text-xs rounded-md transition-colors ${
                      isSelected
                        ? "bg-primary/10 text-primary"
                        : "text-muted-foreground hover-elevate"
                    } ${isLoading ? "opacity-50 cursor-not-allowed" : "cursor-pointer"}`}
                    data-testid={`button-period-${p.value}`}
                  >
                    {p.shortLabel}
                  </button>
                );
              })}
            </div>
            <Button
              variant="ghost"
              size="icon"
              onClick={handleGenerate}
              disabled={isLoading}
              data-testid="button-refresh-insight-header"
            >
              <RefreshCw className={`h-3 w-3 ${isLoading ? "animate-spin" : ""}`} />
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-3 pt-0">
        {hasError ? (
          <div className="flex items-center gap-2 py-2">
            <AlertCircle className="h-4 w-4 text-destructive" />
            <p className="text-xs text-destructive flex-1">{errorMessage}</p>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleGenerate}
              data-testid="button-retry-insight"
            >
              <RefreshCw className="h-3 w-3 mr-1" />
              Retry
            </Button>
          </div>
        ) : isLoading || !insight ? (
          <div className="flex items-center justify-center py-4 gap-2">
            <RefreshCw className="h-4 w-4 text-primary animate-spin" />
            <p className="text-xs text-muted-foreground">Analyzing...</p>
          </div>
        ) : (
          <div className="space-y-2">
            <div className="flex items-start gap-2">
              {getStatusIcon(insight!.status)}
              <div className="flex-1 min-w-0">
                <h3 className="font-medium text-sm leading-tight">{insight!.headline}</h3>
                <div className="flex items-center gap-2 mt-1 flex-wrap">
                  {getStatusBadge(insight!.status)}
                  <div className="flex items-center gap-1 text-xs text-muted-foreground">
                    {getMomentumIcon(insight!.momentum)}
                    <span>
                      {insight!.momentum === "up" ? "Up" : insight!.momentum === "down" ? "Down" : "Steady"}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <p className="text-xs text-muted-foreground leading-relaxed">{insight!.mainInsight}</p>

            <button
              className="flex items-center gap-1 text-xs text-muted-foreground hover-elevate py-1"
              onClick={() => setIsExpanded(!isExpanded)}
              data-testid="button-expand-insight"
            >
              {isExpanded ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
              <span>{isExpanded ? "Less" : "Details"}</span>
            </button>

            {isExpanded && (
              <div className="space-y-2 pt-2 border-t">
                {insight.strengths.length > 0 && (
                  <div>
                    <h4 className="text-xs font-medium text-muted-foreground mb-1 flex items-center gap-1">
                      <CheckCircle2 className="h-3 w-3 text-green-500" />
                      Strengths
                    </h4>
                    <ul className="space-y-0.5">
                      {insight.strengths.map((strength, i) => (
                        <li key={i} className="text-xs text-muted-foreground pl-4">{strength}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {insight.concerns.length > 0 && (
                  <div>
                    <h4 className="text-xs font-medium text-muted-foreground mb-1 flex items-center gap-1">
                      <AlertTriangle className="h-3 w-3 text-yellow-500" />
                      Watch
                    </h4>
                    <ul className="space-y-0.5">
                      {insight.concerns.map((concern, i) => (
                        <li key={i} className="text-xs text-muted-foreground pl-4">{concern}</li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="bg-primary/5 rounded-md p-2">
                  <h4 className="text-xs font-medium mb-0.5 flex items-center gap-1">
                    <Lightbulb className="h-3 w-3 text-primary" />
                    Suggestion
                  </h4>
                  <p className="text-xs">{insight.suggestion}</p>
                </div>

                <div className="flex justify-between text-center pt-2 border-t text-xs">
                  <div>
                    <span className="font-semibold">{insight.daysAnalyzed}</span>
                    <span className="text-muted-foreground ml-1">days</span>
                  </div>
                  <div>
                    <span className="font-semibold">{insight.totalPoints}</span>
                    <span className="text-muted-foreground ml-1">pts</span>
                  </div>
                  <div>
                    <span className="font-semibold">{insight.avgDailyPoints}</span>
                    <span className="text-muted-foreground ml-1">avg/day</span>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
